### ISSUE TITLE
Métaphore

### ISSUE THREAD

**Issue by Knackie** [pBouillon/locutionis#15]
## Détails

c'est comme la comparaison, sans le comme :)

### Nom

> Métaphore

### Description

>Procédé de langage (figure, trope) qui consiste dans une modification de sens (terme concret dans un contexte abstrait) par substitution analogique.

### But

> Métaphorer quelque chose

### Exemples

> Elle le trouvait un homme parfait. (Le père Goriot, Honoré de Balzac) → le (terme métaphorisé), homme parfait (terme métaphorisant).

### Sources

> [[Sources à partir desquelles les informations précédentes ont été trouvées (nom de la source et URL)](](https://www.definitions360.com/exemples-de-la-metaphore/))

---

- [x] Cette figure de style n'est pas référencée dans Locutionis
- [x] Ces informations sont complètes
  - [x] Toutes les sections sont remplies
  - [x] Au moins un exemple est ajouté
  - [x] Les sources sont citées

**Comment by pBouillon** [comment]
Thanks for the suggestion, I'll check it out !
